//Chiamata con ricerca parametro "s" => terminator
GET http://www.omdbapi.com/?apikey=46a5f494&t=Loki HTTP/1.1

###

//Chiamata con ricerca parametro "s" => terminator SOLO PER I MOVIE
GET http://www.omdbapi.com/?apikey=46a5f494&t=terminator&type=movie HTTP/1.1

###

//Chiamata con ricerca parametro "s" SOLO PER SERIES
GET http://www.omdbapi.com/?apikey=46a5f494&t=Marvel&type=series HTTP/1.1

###

//Chiamata con ricerca parametro "s" SOLO PER GAMES
GET http://www.omdbapi.com/?apikey=46a5f494&t=terminator&type=games HTTP/1.1

###

//Chiamata di un dettaglio di un singolo movie
GET http://www.omdbapi.com/?apikey=46a5f494&t=tt0103064 HTTP/1.1

###

//Chiamata per solo determinate pagine

GET http://www.omdbapi.com/?apikey=46a5f494&t=Avengers HTTP/1.1